package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"
	"fmt"

	"github.com/nallj/t2t_app_gateway/graph/model"
)

// GetImage is the resolver for the getImage field.
func (r *queryResolver) GetImage(ctx context.Context, imageID string) (*model.GetImageResponse, error) {
	panic(fmt.Errorf("not implemented: GetImage - getImage"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
